<?php

namespace RTER\ContentBundle\Repository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDistinctCountries()
    {
        $query = $this->createQueryBuilder('e')
//            ->select('id')
//            ->where('e.orderDeadlineDate > :date')
//            ->setParameter('date', date("Y-m-d H:i:s"))
            ->groupBy('e.country')
            ->getQuery();
        return $query->getResult();
    }
}
